GIN-21-Copyright-section-implementation
guisetech/guisetech.com pull request #1
Opened 2023-01-24 11:57 UTC by OnurRozet

Copyright section completed

2023-01-24 15:05 UTC, asozyurt requested changes
I should only see the copyright changes here. it is showing tons of changes.

2023-01-25 08:37 UTC, OnurRozet commented
Copyright Section fixed. Only changed CopyRight

2023-01-25 10:49 UTC, asozyurt requested changes

2023-01-25 10:49 UTC, asozyurt commented on public/index.html
> +      let date = new Date().getFullYear();
no need to use let here

2023-01-25 10:49 UTC, asozyurt commented on public/index.html
> +      let dom = (document.querySelector(".date").innerHTML = date);
why did you define dom ? it is not being used anywhere. Check the scenario that; the query selector cannot find the item. What happens then?

2023-01-28 14:48 UTC, asozyurt approved these changes

2023-01-28 14:48 UTC, merged