GIN-24-Header-simplification-will-be-needed
guisetech/guisetech.com pull request #3
Opened 2023-01-24 12:19 UTC by OnurRozet

Header simplification completed

2023-01-24 22:54 UTC, asozyurt requested changes

2023-01-24 22:54 UTC, asozyurt commented on public/index.html
>                                   <li class="has-dropdown">
Services is not a dropdown.

2023-01-25 06:38 UTC, OnurRozet commented
services section fixed

2023-01-25 10:47 UTC, asozyurt approved these changes

2023-01-25 10:47 UTC, merged